### ISSUE TITLE
Some "touches" do not disappear

### ISSUE THREAD

**Issue by ffittschen** [asafkorem/COSTouchVisualizer#17]
Sometimes the visualized touches do not disappear. But they still do that jellyfish movement. The problem occurs randomly, sadly I haven't found a way to reproduce it. The project is entirely written in swift and the COSTouchVisualizer (1.0.3) is added via CocoaPods. Do you have any idea what the cause could be?

![foto 20 01 15 23 06 48](https://cloud.githubusercontent.com/assets/7734806/5827355/f05fa3e0-a0f9-11e4-8f13-d64dfb7be435.png)

**Comment by joeblau** [comment]
Yeah, I think someone submitted a PR for this.  I've just been busy.  I'll try and merge it in and update the library this weekend.

**Comment by rodrigoelp** [comment]
One way to reproduce it is to segue from a to b while holding down a tap. (At least that was the way I managed to reproduce it on my app)

**Comment by joeblau** [comment]
I've been able to reproduce it so I'll have to look into what's going on.  Thanks for finding this; it wasn't caught in the latest update.

**Comment by joeblau** [comment]
This was fixed in 393debeb77d1e87fc036df3ec42969d2fe3a57b1
