### ISSUE TITLE
COSTouchVisualizer broken for swift projects

### ISSUE THREAD

**Issue by rodrigoelp** [asafkorem/COSTouchVisualizer#20]
Hey guys, I have submitted a pull request that fixes compilation issues for swift projects. Added some description to the pull request.

https://github.com/conopsys/COSTouchVisualizer/pull/19 

Let me know if there is something else that needs to be done.
Cheers!

**Comment by joeblau** [comment]
PR merged in and pushed a new 1.0.5 build up to the main Cocoapods repo.

**Comment by rodrigoelp** [comment]
Cool, thanks Joe
