### ISSUE TITLE
Swift 3 issue

### ISSUE THREAD

**Issue by zigzagg16** [asafkorem/COSTouchVisualizer#25]
I'm using Swift 3, and the sample code.
When compiling, I get this error: 

> Command failed due to signal: Segmentation fault: 11
> 1.	While emitting SIL for getter for window at /AppDelegate.swift:14:14

By removing the lazy keyword, this error disappears, but I got a new error at: 
`customWindow.touchVisualizerWindowDelegate = self`

Any idea to solve this issue ?

Thx,
Arnaud

**Comment by joeblau** [comment]
I've update the example, but I should really have a better way for configuring the touch window.

**Comment by zigzagg16** [comment]
Awesome, thanks a lot ! 👍

**Comment by joeblau** [comment]
Oh and here is the new version I'm working on too:

https://github.com/design-utilities/sensor-visualizer

It's not done and there are still some things I need to figure out.  I also might change the API so I wouldn't' count on it yet, but it's a work in progress.
