### ISSUE TITLE
The Copy Bundle Resources build phase contains this target's Info.plist file

### ISSUE THREAD

**Issue by JonasGessner** [asafkorem/COSTouchVisualizer#26]
The framework target contains its own Info.plist file in the copy bundle resources phase. The Info.plist doesn't need to be in the copy bundle resources phase and it causes a warning when building the framework. It's not causing any actual bugs but I'd appreciate if you could remove the file from the copy bundle resources phase anyway!

**Comment by joeblau** [comment]
Thanks for catching this 👍 - I'll create a new version of the Pod over the weekend.
