### ISSUE TITLE
Touch visualiser on single view

### ISSUE THREAD

**Issue by ajaysinghthakur** [asafkorem/COSTouchVisualizer#30]
want to see touch on single uiview not on uiwindow. is that possible?

**Comment by joeblau** [comment]
Unfortunately, not with the current state of this project.  Right now it's all or nothing.

**Comment by ajaysinghthakur** [comment]
I modified your work  To work on single view here is the link to it -https://github.com/ajaysinghthakur/ASTTouchVisualizeView

**Comment by joeblau** [comment]
I've got another project I'm working on for visualizing all sensor information.  Maybe I can eventually incorporate this into that project.

![sv](https://user-images.githubusercontent.com/1218847/28370120-8085ae7a-6c67-11e7-8935-02d0c745c336.gif)
