### ISSUE TITLE
How can I switch between visibility mode?

### ISSUE THREAD

**Issue by S2V** [asafkorem/COSTouchVisualizer#33]
How can I switch between visibility mode? Before refactoring to modern Objective-C, visibility was controlled `- (BOOL)isActive` method. But after refactoring - we have read-only `COSTouchVisualizerWindowTouchVisibility`.

**Comment by joeblau** [comment]
You should be using the [tag](https://github.com/conopsys/COSTouchVisualizer/releases/tag/1.0.6), not the latest master.  I'm trying to clean this up to make it easier to read.  I got started, but I'm not done.  I'm trying to clean it up and still maintain backwards compatibility :).

**Comment by LeoNatan** [comment]
The tag is from 2015 which is buggy and there have been improvements since then. Mind releasing a new tag at commit ad729c993de213ccb6be6af30c4bb5730293231c ?

**Comment by joeblau** [comment]
Hey, there haven't been any improvements.  I'm actually working on a new library for all sensors in Swift, but I've been waiting on Source / ABI stability to release it.  Next weekend I'll cut a new tag with the updates.

**Comment by LeoNatan** [comment]
Looking at the commits, there have been several fixes:

https://github.com/conopsys/COSTouchVisualizer/commit/82c21958e12b06f2a5b83066717291bc53d5cbb3
https://github.com/conopsys/COSTouchVisualizer/commit/21f7f1af4ff6eafeaa807aa2d2844770b914d0a6
https://github.com/conopsys/COSTouchVisualizer/commit/59992972e0ee0073054f01035c67a70a9efeacea
